// <auto-generated />
namespace CarDealership2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class reset2add2dbcontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reset2add2dbcontext));
        
        string IMigrationMetadata.Id
        {
            get { return "202102201752390_reset2add2dbcontext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
