// <auto-generated />
namespace CarDealership2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addpurchasetable2db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpurchasetable2db));
        
        string IMigrationMetadata.Id
        {
            get { return "202103202106508_addpurchasetable2db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
